# Site settings
author: Justin Winger
title: Software Development
header-img: img/home-bg.png
email: justinwinger4@gmail.com
copyright_name: Justin Winger
description: > # this means to ignore newlines until "baseurl:"
  Why I decided to learn software development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: wipletree
github_username:  wingerwingman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
